apiVersion: v1
kind: PersistentVolume
metadata:
  name: chargement-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: appex-chargement
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chargement-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: chargement-volume
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
